// AUTO-GENERATED from the live arcada backend. Do not edit by hand.
namespace FloorPlan.Editor;

public static partial class Catalog
{
    public static readonly IReadOnlyList<CatalogItem> Imported = new List<CatalogItem>
    {
        new("bathtub", "Bathtub", "Bathroom", 1, 2, "#e9edf2", "", "furniture/bathtub.svg"),
        new("bathtub-corner", "Bathtub - corner", "Bathroom", 2, 2, "#e9edf2", "", "furniture/bathtub-corner.svg"),
        new("bathtub-oval", "Bathtub - oval", "Bathroom", 1.2, 2, "#e9edf2", "", "furniture/bathtub-oval.svg"),
        new("bidet", "Bidet", "Bathroom", 0.6, 0.8, "#e9edf2", "", "furniture/bidet.svg"),
        new("corner-sink", "Corner sink", "Bathroom", 0.7, 0.7, "#e9edf2", "", "furniture/corner-sink.svg"),
        new("round-sink", "Round sink", "Bathroom", 0.7, 0.7, "#e9edf2", "", "furniture/round-sink.svg"),
        new("shower", "Shower", "Bathroom", 1.1, 1.1, "#e9edf2", "", "furniture/shower.svg"),
        new("bathroomsink", "Sink", "Bathroom", 0.8, 0.6, "#e9edf2", "", "furniture/bathroomsink.svg"),
        new("toilet", "Toilet", "Bathroom", 0.7, 1, "#e9edf2", "", "furniture/toilet.svg"),
        new("washing-machine", "Washing Machine", "Bathroom", 0.7, 0.7, "#e9edf2", "", "furniture/washing-machine.svg"),
        new("bedside-rug", "Bedside rug", "Bedroom", 0.8, 1.2, "#e9edf2", "", "furniture/bedside-rug.svg"),
        new("bedside-table", "Bedside table 1", "Bedroom", 0.8, 0.5, "#e9edf2", "", "furniture/bedside-table.svg"),
        new("noptiera", "Bedside table 2", "Bedroom", 0.8, 0.5, "#e9edf2", "", "furniture/noptiera.svg"),
        new("chair-1", "Chair", "Bedroom", 0.6, 0.6, "#e9edf2", "", "furniture/chair-1.svg"),
        new("king-size-bed", "Double bed", "Bedroom", 1.6, 2, "#e9edf2", "", "furniture/king-size-bed.svg"),
        new("large-plant", "Large plant", "Bedroom", 1, 1, "#e9edf2", "", "furniture/large-plant.svg"),
        new("lounge-chair", "Lounge chair", "Bedroom", 0.8, 0.9, "#e9edf2", "", "furniture/lounge-chair.svg"),
        new("round-rug", "Oval rug", "Bedroom", 1.5, 1, "#e9edf2", "", "furniture/round-rug.svg"),
        new("round-table", "Round table - Small", "Bedroom", 0.6, 0.6, "#e9edf2", "", "furniture/round-table.svg"),
        new("twin-size-bed", "Single bed", "Bedroom", 1, 2, "#e9edf2", "", "furniture/twin-size-bed.svg"),
        new("table", "Table", "Bedroom", 1.2, 0.8, "#e9edf2", "", "furniture/table.svg"),
        new("wardrobe-large", "Wardrobe - large", "Bedroom", 2.5, 0.8, "#e9edf2", "", "furniture/wardrobe-large.svg"),
        new("drawer", "Wardrobe - small", "Bedroom", 1.5, 1, "#e9edf2", "", "furniture/drawer.svg"),
        new("bar-counter", "Bar counter", "Kitchen", 1.6, 0.6, "#e9edf2", "", "furniture/bar-counter.svg"),
        new("bar-stool", "Bar stool", "Kitchen", 0.55, 0.5, "#e9edf2", "", "furniture/bar-stool.svg"),
        new("countertop-corner", "Countertop - corner", "Kitchen", 0.9, 0.9, "#e9edf2", "", "furniture/countertop-corner.svg"),
        new("chair-2", "Dinner chair - variant 1", "Kitchen", 0.7, 0.7, "#e9edf2", "", "furniture/chair-2.svg"),
        new("chair-3", "Dinner chair - variant 2", "Kitchen", 0.6, 0.85, "#e9edf2", "", "furniture/chair-3.svg"),
        new("dining-table-square", "Dinner table - 4 people", "Kitchen", 1, 1, "#e9edf2", "", "furniture/dining-table-square.svg"),
        new("dining-table-6", "Dinner table - 6 people", "Kitchen", 1.6, 0.9, "#e9edf2", "", "furniture/dining-table-6.svg"),
        new("dishwasher", "Dishwasher", "Kitchen", 0.7, 0.7, "#e9edf2", "", "furniture/dishwasher.svg"),
        new("double-sink", "Double kitchen sink", "Kitchen", 1.2, 0.6, "#e9edf2", "", "furniture/double-sink.svg"),
        new("kitchenfridge", "Fridge", "Kitchen", 0.6, 0.6, "#e9edf2", "", "furniture/kitchenfridge.svg"),
        new("fume-hood-md", "Fume hood", "Kitchen", 0.6, 0.4, "#e9edf2", "", "furniture/fume-hood-md.svg"),
        new("kitchen-sink-corner", "Kitchen sink - corner", "Kitchen", 1, 0.55, "#e9edf2", "", "furniture/kitchen-sink-corner.svg"),
        new("farfurie-furculita", "Plate", "Kitchen", 0.25, 0.2, "#e9edf2", "", "furniture/farfurie-furculita.svg"),
        new("kitchensink", "Sink", "Kitchen", 1, 0.6, "#e9edf2", "", "furniture/kitchensink.svg"),
        new("stove", "Stove - 4 spots", "Kitchen", 0.6, 0.6, "#e9edf2", "", "furniture/stove.svg"),
        new("5-spot-hob", "Stove - 5 spots", "Kitchen", 0.8, 0.6, "#e9edf2", "", "furniture/5-spot-hob.svg"),
        new("armchair", "Armchair", "Living Room", 1.2, 1, "#e9edf2", "", "furniture/armchair.svg"),
        new("couch", "Couch", "Living Room", 2.4, 1, "#e9edf2", "", "furniture/couch.svg"),
        new("loveseat", "Couch - 2 seats", "Living Room", 1.8, 1, "#e9edf2", "", "furniture/loveseat.svg"),
        new("plant", "Plant 1", "Living Room", 0.6, 0.6, "#e9edf2", "", "furniture/plant.svg"),
        new("potted-plant-2", "Plant 2", "Living Room", 0.6, 0.6, "#e9edf2", "", "furniture/potted-plant-2.svg"),
        new("potted-plant-1", "Plant 3", "Living Room", 0.6, 0.6, "#e9edf2", "", "furniture/potted-plant-1.svg"),
        new("sectional-couch-corner-seat", "Sectional couch - corner seat", "Living Room", 0.7, 0.7, "#e9edf2", "", "furniture/sectional-couch-corner-seat.svg"),
        new("sectional-couch-seat", "Sectional couch - front seat", "Living Room", 0.7, 0.7, "#e9edf2", "", "furniture/sectional-couch-seat.svg"),
        new("televizor", "TV", "Living Room", 1.1, 0.15, "#e9edf2", "", "furniture/televizor.svg"),
        new("computer", "Computer", "Office", 0.8, 0.4, "#e9edf2", "", "furniture/computer.svg"),
        new("computer-monitor", "Computer monitor", "Office", 0.8, 0.1, "#e9edf2", "", "furniture/computer-monitor.svg"),
        new("corner-desk", "Corner desk", "Office", 1, 1.5, "#e9edf2", "", "furniture/corner-desk.svg"),
        new("car", "Car", "Other", 4, 2, "#e9edf2", "", "furniture/car.svg"),
        new("generic-object", "Generic object", "Other", 0.5, 0.5, "#e9edf2", "", "furniture/generic-object.svg"),
        new("pantofar", "Shoe rack", "Other", 1.1, 0.4, "#e9edf2", "", "furniture/pantofar.svg"),
        new("welcome", "Welcome mat", "Other", 0.6, 0.3, "#e9edf2", "", "furniture/welcome.svg"),
        new("stair-cover", "Stair cover", "Structural", 1, 1.5, "#e9edf2", "", "furniture/stair-cover.svg"),
        new("stairs-corner", "Staircase - corner", "Structural", 3, 3, "#e9edf2", "", "furniture/stairs-corner.svg"),
        new("stairs-lg-sq", "Staircase - long", "Structural", 2, 4, "#e9edf2", "", "furniture/stairs-lg-sq.svg"),
        new("stairs-md-sq", "Staircase - medium", "Structural", 2, 2, "#e9edf2", "", "furniture/stairs-md-sq.svg"),
        new("stairs-round", "Staircase - round", "Structural", 3, 3, "#e9edf2", "", "furniture/stairs-round.svg"),
        new("stairs-small-sq", "Staircase - small", "Structural", 2, 1.6, "#e9edf2", "", "furniture/stairs-small-sq.svg"),
    };

    public static readonly CatalogItem DoorImg = new("door", "Door", "_special", 1, 1, "#c79a5b", "door", "furniture/door-exterior.svg");
    public static readonly CatalogItem WindowImg = new("window", "Window", "_special", 1, 0.15, "#7fbfe0", "window", "furniture/window.svg");
    public static readonly IReadOnlyList<string> ImportedCategories = new[]{ "Bedroom", "Bathroom", "Kitchen", "Office", "Living Room", "Other", "Structural" };
}
